### PR TITLE
Refactor `obj!` and `obj` functions

### PR DESCRIPTION
**Pull request by tmigot**
@MonssafToukal This should make more sense now. Let me know what you think?
I renamed `obj!` because the `!` is usually for in-place functions

### CODE REVIEW

**Comment by MonssafToukal** [comment]
It makes more sense to call it `obj` without the `!`. Perhaps the only issue I have is the `obj`  method I use to tune with NOMAD.jl. I recently modified its signature to be `function obj!(nlp::BBModel, p::Problem)` instead of `function obj!(nlp::BBModel, p::Problem, x::AbstractVector)`. I think we should have a quick chat to explain why I am doing it like this. Other than that, it's perfect. I like that you added the parameters for benchmarking in the signature :)

**Comment by tmigot** [comment]
Ok, then it feels like the best is to define `obj!(nlp, p) = obj(nlp, p, values(p))` in your other code. What do you think?
Because, independently of this specific motivation, I don't really see the motivation.

**Comment by tmigot** [comment]
Oh wait, the problem is that `solver_func` has the signature `(nlp, p) -> GenericExecutionStats` so it is weird to pass an `x`. Is that the problem?

**Comment by tmigot** [comment]
@MonssafToukal I changed it again to keep the old signature.

**Comment by MonssafToukal** [comment]
> Oh wait, the problem is that `solver_func` has the signature `(nlp, p) -> GenericExecutionStats` so it is weird to pass an `x`. Is that the problem?

Exactly! Now I simply use the parameter_set stored inside the bbmodel and I update their values b the ones given by NOMAD. You can take a look here: https://github.com/ProofOfConceptForJuliSmoothOptimizers/SolverTuning.jl/blob/rework-module/src/nomad_interface.jl#L101

**Comment by MonssafToukal** [comment]
I you look at this line: https://github.com/ProofOfConceptForJuliSmoothOptimizers/SolverTuning.jl/blob/rework-module/src/run_bb_model.jl#L7 I use the `obj(bbmodel, nlp)` signature, but with this change, I should do a `cost(bbmodel, nlp)` and then use the `p_metric` returned and manually evaluate `bbmodel.auxiliary_function(p_metric)`.

**Pull request merged**
